# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'Assignment' do
    pod 'AlamofireImage', '~> 3.5'
end
